#!/bin/sh

if [ $# -ne 1 ]; then
	echo "This scripts iterate through all Samples/ in a Project/ and runs the Makefile (the preprocess pipeline)"
	echo "--------------------------------------------------------------------------------------------------------------------------"
	echo "Usage: $(basename $0) <Project Folder>"
	exit
fi

#Define File Location
#====================
# Define path to Project Folder
if [ ! -d "$1" ]; then
	echo "Error: Project Folder does not exist"
	exit 1
fi

PROJECT_FOLDER=$(readlink -f "$1")

# Extract Project ID from the path: Assumes form is "Project_PROJECT_NAME"
PROJECT_ID=$(echo `basename $PROJECT_FOLDER` | cut -d "_" -f 2-)

# Main Script
# ===========
#Create Make Files for each sample found in Project folder
for i in $(ls $PROJECT_FOLDER); do 
	
	if [ -d "$PROJECT_FOLDER/$i" ]; then

		SAMPLE_FOLDER="$PROJECT_FOLDER/$i"
		cd "$SAMPLE_FOLDER/"
		
		echo "Building Makefile for $SAMPLE_FOLDER..."
		nohup make &

		# Currently waits for Make (Don't know how many concurrent preprocessing threads to spawn on the analysis server)
		PID_MAKE=$!
		wait $PID_MAKE
		
		# Display corresponding status message for 
		# if [ $? -eq 0 ]; then
		#	echo "Build completed successfully for $SAMPLE_FOLDER"
		# else
		#	echo "Build terminated with error for $SAMPLE_FOLDER"
		# fi
	fi
done

