#!/bin/bash

if [ $# -ne 2 ]; then
        echo "This scripts iterate through all Samples/ in a Project/ and runs the Makefile (the preprocess pipeline)"
        echo "--------------------------------------------------------------------------------------------------------------------------"
        echo "Usage: $(basename $0) <project name> <sample name>"
        exit
fi

project=$1
sample=$2

#$ -S /bin/bash
#$ -m ae
#$ -M sge_test
#$ -o $HOME/logs/preprocess/gatk.process/$JOB_NAME.o
#$ -j y

java -Xmx12g -jar /data1/queue/Queue/Queue.jar \
-S /data1/queue/qscripts/DataProcessingPipeline.scala \
-p $project -sg 0 -i $sample.sorted.bam -R $REF -D $DBSNP \
-indels /data1/gatk_resources_1_5/1000G_phase1.indels.hg19.vcf.gz \
-indels /data1/gatk_resources_1_5/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz \
-tempDir ./tmp -startFromScratch \
-jobReport $sample.jobreport -l INFO -run 

wait $!

if [ $? -gt 0 ]; 
then
	exit 1
fi
