#!/bin/sh
#
if [ $# -ne 1 ]; then
	echo "This script runs through the data folder to remove old unneeded files"
	echo "---------------------------------------------------------------------"
	echo "Usage: $(basename $0) <Data2 Folder>"
	exit
fi

#Define File Location
#====================
if [ ! -d "$1" ]; then
	echo "Error: Data2 Folder does not exist"
	exit
fi

IN_FOLDER=$(readlink -f "$1")

# Main Script
# ===========
echo "Recursively going through Data2 to remove unneeded files defined in file2del.txt"

cat $NGS_PIPE/helpers/cleanup/file2del.txt | while read LINE
do
	echo "$LINE"

	for RMV_FILE in $(find $IN_FOLDER | grep "$LINE$"); do

		echo "$RMV_FILE"
		#rm "$RMV_FILE"
	done
done

END_TIME=$(date +%y.%m.%d\|%H:%M:%S)

